### PR TITLE
add requirements for supporting packages; build and test in docker; jenkins CI testing

### PR DESCRIPTION
**Pull request by mwes**
Do not merge until we resolve what looks like a pySBOL/libSBOL issue so CI tests pass on Ubuntu (they pass on OSX): https://sd2e-jira.tacc.utexas.edu/browse/SD2-264

### CODE REVIEW

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
14th time is the charm: http://jenkins.sd2e.org/job/synbiohub_adapter/14/
@t

**Comment by mwes** [comment]
@nroehner @tramyn I worked through getting a Docker build+test on Jenkins with @tcmitchell. Let me know if you have any concerns. I prefer to have someone besides the author review and merge a pull request. Thanks!

**Comment by tramyn** [comment]
@mwes, this is my concern. I'm not too familiar with setting up a Docker but it looks like your Docker is building off of python2. This project and the pySBOL library used in this project is using python 3.6.

**Comment by mwes** [comment]
OK - although many parts of SD2 are Python3 compatible, I know not all are. So we may want to expose some sort of proxy around a containerized instance of this library for those who can't import it directly. I can adjust this to use python3 to be in line with pySBOL, etc.

**Comment by mwes** [comment]
@tcmitchell, which version of Python3 did you build your wheel from? And I (probably) need to update the shared library?

It looks like the SD2 base image uses python 3.5.2. I'll see if I can update it.
```
root@903bda5d295f:/usr/local/lib/python3.5# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
```

```
======================================================================
ERROR: test_SPARQLQueries (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_SPARQLQueries
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/scripts/tests/test_SPARQLQueries.py", line 3, in <module>
    from query_synbiohub import *
  File "/opt/scripts/query_synbiohub.py", line 5, in <module>
    from sbol import *
  File "/usr/local/lib/python3.5/dist-packages/sbol/__init__.py", line 5, in <module>
    from sbol.libsbol import *
  File "/usr/local/lib/python3.5/dist-packages/sbol/libsbol.py", line 31, in <module>
    _libsbol = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/sbol/libsbol.py", line 27, in swig_import_helper
    _mod = imp.load_module('_libsbol', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/libsbol.so: undefined symbol: PyUnicodeUCS4_FromString
```

**Comment by tcmitchell** [comment]
I built on Ubuntu 16.04 with python3 3.5.2:

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
```

You now need to:

* update the wheel URL from post10 to post11 (keep Ubuntu_16.04_64_3)
* update the library URL from Ubuntu_16.04_64_2 to Ubuntu_16.04_64_3

**Comment by mwes** [comment]
Thanks @tcmitchell! @tramyn we're building and running now on 3.5.2, which is what the SD2 base python 3 image has.  I am working with Matt Vaughn to get that upgraded. Can you confirm the version you and Nic are using with PySBOL and this library? 3.6.4?

**Comment by nroehner** [comment]
I made my Windows build of pySBOL with Python 3.6.2 and have been running
synbiohub_adapter with these.

**Comment by mwes** [comment]
The image now has python 3.6. Tom is working on getting an updated wheel for 3.6 and removing the libsbol.so manual copying. After that we should be in business.

**Comment by mwes** [comment]
Docker build and test works on Python 3.6.4. @nroehner @tramyn can this merged?

**Comment by tramyn** [comment]
@mwes Yes. I'm fine with your merge. I've moved some files around so I hope it won't affect your merging process.

**Pull request merged**
