### PR TITLE
Filter members of a Collection that match a substring

### PR DESCRIPTION
**Pull request by bbartley**
Implements a SPARQL query that filters the members of a Collection by a substring. 

Example:
```
q = SynBioHubQuery('https://synbiohub.utah.edu')
q.login(username, password).
q.filter(target_collection_uri, search_substring)
```

### CODE REVIEW

**Comment by mwes** [comment]
Can one of the admins verify this patch?

**Comment by tcmitchell** [comment]
@bbartley @mwes what is the status of this pull request?

The comments above indicate that it should be reviewed. It has also fallen behind and has conflicts. If it is live, it should be updated, reviewed, and assigned a milestone.

**Comment by mwes** [comment]
Suggest @bbartley review and update as needed.

**Comment by bbartley** [comment]
This PR just adds an additional query that will be useful for the SD2 "back-builder" application.  It should not need any major review, just making everyone aware that it exists.

**Comment by mwes** [comment]
Jenkins, build this please.

**Comment by mwes** [comment]
Jenkins, build this please.

**Comment by mwes** [comment]
Jenkins, build this please.

**Pull request merged**
